name: grocery_list_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_slidable: ^3.1.1
  flutter_tts: ^4.2.0
  hive_flutter: ^1.1.0
  http: ^1.2.2
  lottie: ^3.1.3
  openai_api: ^0.3.7
  openai_dart: ^0.4.4
  provider: ^6.1.2
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
